export const perguntas_e_respostas = [
  {"pergunta": "Qual é a altura do Monte Everest?", "resposta": 8848}, 
  {"pergunta": "Quantos países compõem a União Europeia?", "resposta": 27},
  {"pergunta": "Qual é a capital do Quênia?", "resposta": "Nairobi"},
  {"pergunta": "Quantos elementos químicos existem na tabela periódica?", "resposta": 118},
  {"pergunta": "Em que ano foi assinada a Independência do Brasil?", "resposta": 1822},
  {"pergunta": "Quantos ossos tem o corpo humano?", "resposta": 206},
  {"pergunta": "Qual é a velocidade da luz no vácuo?", "resposta": 299792458},
  {"pergunta": "Quantos continentes existem?", "resposta": 7},
  {"pergunta": "Em que ano a Primeira Guerra Mundial começou?", "resposta": 1914},
  {"pergunta": "Qual é o maior planeta do sistema solar?", "resposta": "Júpiter"},
  {"pergunta": "Quantos anos tem a Grande Muralha da China?", "resposta": 2000},
  {"pergunta": "Quem foi o primeiro presidente dos Estados Unidos?", "resposta": "George Washington"},
  {"pergunta": "Quantas patas tem um inseto?", "resposta": 6},
  {"pergunta": "Qual é o animal terrestre mais rápido?", "resposta": "Guepardo"},
  {"pergunta": "Quantas cartas tem um baralho comum?", "resposta": 52},
  {"pergunta": "Em que ano a Revolução Francesa começou?", "resposta": 1789},
  {"pergunta": "Qual é a capital da Austrália?", "resposta": "Camberra"},
  {"pergunta": "Quantos oceanos existem?", "resposta": 5},
  {"pergunta": "Quem escreveu 'Romeu e Julieta'?", "resposta": "William Shakespeare"},
  {"pergunta": "Quantos dentes permanentes tem um ser humano?", "resposta": 32},
  {"pergunta": "Qual é o maior deserto do mundo?", "resposta": "Deserto da Antártida"},
  {"pergunta": "Quantos quilômetros quadrados tem a Amazônia?", "resposta": 5500000},
  {"pergunta": "Em que ano a internet foi inventada?", "resposta": 1969},
  {"pergunta": "Qual é o maior mamífero terrestre?", "resposta": "Elefante africano"},
  {"pergunta": "Quantos planetas do sistema solar têm anéis?", "resposta": 4},
  {"pergunta": "Quem pintou a Mona Lisa?", "resposta": "Leonardo da Vinci"},
  {"pergunta": "Quantos anos vive um panda em cativeiro?", "resposta": 30},
  {"pergunta": "Qual é a velocidade do som no ar?", "resposta": 343},
  {"pergunta": "Quantos países existem na América do Sul?", "resposta": 12},
  {"pergunta": "Quem foi o primeiro ser humano a viajar para o espaço?", "resposta": "Yuri Gagarin"},
  {"pergunta": "Quantos quilômetros tem a Grande Muralha da China?", "resposta": 21196},
  {"pergunta": "Qual é a capital do Canadá?", "resposta": "Ottawa"},
  {"pergunta": "Quantos anos durou a Segunda Guerra Mundial?", "resposta": 6},
  {"pergunta": "Quem foi o inventor do telefone?", "resposta": "Alexander Graham Bell"},
  {"pergunta": "Quantos dentes temporários tem um ser humano?", "resposta": 20},
  {"pergunta": "Qual é a montanha mais alta do Brasil?", "resposta": "Pico da Neblina"},
  {"pergunta": "Quantos anos a Lua demora para dar uma volta completa na Terra?", "resposta": 27.3},
  {"pergunta": "Quem escreveu 'Cem Anos de Solidão'?", "resposta": "Gabriel García Márquez"},
  {"pergunta": "Quantos tentáculos tem um polvo?", "resposta": 8},
  {"pergunta": "Qual é o maior lago de água doce do mundo?", "resposta": "Lago Baikal"},
  {"pergunta": "Quantos planetas anões existem no sistema solar?", "resposta": 5},
  {"pergunta": "Quem foi o primeiro presidente do Brasil?", "resposta": "Marechal Deodoro da Fonseca"},
  {"pergunta": "Quantos músculos tem o corpo humano?", "resposta": 600},
  {"pergunta": "Qual é a capital da Argentina?", "resposta": "Buenos Aires"},
  {"pergunta": "Quantos anos dura um mandato presidencial nos Estados Unidos?", "resposta": 4},
  {"pergunta": "Quem foi o fundador da Microsoft?", "resposta": "Bill Gates"},
  {"pergunta": "Quantos ossos tem um recém-nascido?", "resposta": 270},
  {"pergunta": "Qual é o maior rio do mundo em volume de água?", "resposta": "Amazonas"},
  {"pergunta": "Quantos anos tem a Terra?", "resposta": 4.5e9},
  {"pergunta": "Quem foi o primeiro homem a pisar na Lua?", "resposta": "Neil Armstrong"},
  {"pergunta": "Quantos anos vive um golfinho em média?", "resposta": 25},
  {"pergunta": "Qual é o animal mais rápido do planeta?", "resposta": "Falcão peregrino"},
  {"pergunta": "Quantas cores tem o arco-íris?", "resposta": 7},
  {"pergunta": "Quem foi o pintor do quadro 'Noite Estrelada'?", "resposta": "Vincent van Gogh"},
  {"pergunta": "Quantas vértebras tem a coluna vertebral humana?", "resposta": 33},
  {"pergunta": "Qual é o segundo maior planeta do sistema solar?", "resposta": "Saturno"},
  {"pergunta": "Quantas luas tem o planeta Marte?", "resposta": 2},
  {"pergunta": "Quem escreveu 'Dom Quixote'?", "resposta": "Miguel de Cervantes"},
  {"pergunta": "Quantas câmaras tem o coração humano?", "resposta": 4},
  {"pergunta": "Qual é o animal mais pesado do mundo?", "resposta": "Baleia azul"},
  {"pergunta": "Quantos anos tem a rainha Elizabeth II?", "resposta": 96},
  {"pergunta": "Quem foi o cientista que formulou a teoria da relatividade?", "resposta": "Albert Einstein"},
  {"pergunta": "Quantos anos vive um coelho em média?", "resposta": 10},
  {"pergunta": "Qual é o país mais populoso do mundo?", "resposta": "China"},
  {"pergunta": "Quantos quilômetros tem a Muralha da China?", "resposta": 21196},
  {"pergunta": "Quem foi o líder da Revolução Cubana?", "resposta": "Fidel Castro"},
  {"pergunta": "Quantos dentes tem um adulto?", "resposta": 32},
  {"pergunta": "Qual é o rio mais longo do mundo?", "resposta": "Nilo"},
  {"pergunta": "Quantos anos tem a Mona Lisa?", "resposta": 515},
  {"pergunta": "Quem foi o primeiro imperador do Brasil?", "resposta": "Dom Pedro I"},
  {"pergunta": "Quantos anos tem a Estátua da Liberdade?", "resposta": 136},
  {"pergunta": "Qual é o animal mais venenoso do mundo?", "resposta": "Água-viva-caixa"},
  {"pergunta": "Quantos músculos tem o olho humano?", "resposta": 6},
  {"pergunta": "Quem foi o primeiro ser humano a completar uma órbita ao redor da Terra?", "resposta": "Yuri Gagarin"},
  {"pergunta": "Quantos anos tem o Universo?", "resposta": 13.8e9},
  {"pergunta": "Qual é o menor país do mundo?", "resposta": "Vaticano"},
  {"pergunta": "Quantos elementos químicos são gases à temperatura ambiente?", "resposta": 11},
  {"pergunta": "Quem foi o primeiro presidente negro dos Estados Unidos?", "resposta": "Barack Obama"},
  {"pergunta": "Quantos ossos tem um adulto?", "resposta": 206},
  {"pergunta": "Qual é o maior oceano do mundo?", "resposta": "Pacífico"},
  {"pergunta": "Quantos anos vive um elefante em média?", "resposta": 60},
  {"pergunta": "Quem foi o primeiro astronauta a caminhar na Lua?", "resposta": "Neil Armstrong"},
  {"pergunta": "Quantos anos vive um corvo em média?", "resposta": 15},
  {"pergunta": "Qual é o animal mais longevo do planeta?", "resposta": "Tartaruga"},
  {"pergunta": "Quantos minutos tem uma hora?", "resposta": 60},
  {"pergunta": "Quem foi o primeiro homem a circunavegar a Terra?", "resposta": "Fernão de Magalhães"},
  {"pergunta": "Quantos anos vive um tubarão em média?", "resposta": 20},
  {"pergunta": "Qual é o país com a maior população muçulmana?", "resposta": "Indonésia"},
  {"pergunta": "Quantos anos tem a Torre Eiffel?", "resposta": 133},
  {"pergunta": "Quem foi o primeiro presidente do Brasil eleito pelo voto direto após o regime militar?", "resposta": "Fernando Collor"},
  {"pergunta": "Quantos segundos tem um minuto?", "resposta": 60},
  {"pergunta": "Qual é o maior deserto do mundo?", "resposta": "Deserto da Antártida"},
  {"pergunta": "Quantos anos tem a Rainha Elizabeth II no trono?", "resposta": 70},
  {"pergunta": "Quem foi o líder da Revolução Russa?", "resposta": "Vladimir Lenin"},
  {"pergunta": "Quantos ossos tem um recém-nascido?", "resposta": 270},
  {"pergunta": "Qual é o maior país da América do Sul em área territorial?", "resposta": "Brasil"},
  {"pergunta": "Quantos anos durou a Guerra Fria?", "resposta": 45},
  {"pergunta": "Quem foi o primeiro homem a criar um computador?", "resposta": "Charles Babbage"},
  {"pergunta": "Quantos anos vive um orangotango em média?", "resposta": 40},
  {"pergunta": "Qual é o segundo planeta mais próximo do Sol?", "resposta": "Vênus"},
  {"pergunta": "Quantos elementos químicos são líquidos à temperatura ambiente?", "resposta": 2},
  {"pergunta": "Quem foi o primeiro homem a criar uma vacina?", "resposta": "Edward Jenner"},
  {"pergunta": "Quantos anos tem a Grande Muralha da China?", "resposta": 2000},
  {"pergunta": "Qual é o animal mais alto do mundo?", "resposta": "Girafa"},
  {"pergunta": "Quantos estados tem os Estados Unidos?", "resposta": 50},
  {"pergunta": "Quem foi o primeiro imperador romano?", "resposta": "Otávio Augusto"},
  {"pergunta": "Quantos anos vive um leão em média?", "resposta": 20},
  {"pergunta": "Qual é o maior lago da África?", "resposta": "Lago Vitória"},
  {"pergunta": "Quantos ossos tem o crânio humano?", "resposta": 22},
  {"pergunta": "Quem foi o primeiro homem a escalar o Monte Everest?", "resposta": "Edmund Hillary"},
  {"pergunta": "Quantos anos vive uma baleia jubarte em média?", "resposta": 50},
  {"pergunta": "Qual é o país mais populoso da África?", "resposta": "Nigéria"},
  {"pergunta": "Quantos anos tem a Estátua da Liberdade?", "resposta": 136},
  {"pergunta": "Quem foi o primeiro homem a atingir o Polo Sul?", "resposta": "Roald Amundsen"},
  {"pergunta": "Quantos anos vive um tigre em média?", "resposta": 15},
  {"pergunta": "Qual é o maior rio do mundo em extensão?", "resposta": "Nilo"},
  {"pergunta": "Quantas cartas tem um baralho de tarô?", "resposta": 78},
  {"pergunta": "Qual é a capital do Brasil?", "resposta": "Brasília"},
  {"pergunta": "Quantos planetas existem no sistema solar?", "resposta": "Oito"},
  {"pergunta": "Em que ano foi descoberto o Brasil?", "resposta": "1500"},
  {"pergunta": "Qual é o animal terrestre mais rápido?", "resposta": "Guepardo"},
  {"pergunta": "Quem escreveu 'Dom Quixote'?", "resposta": "Miguel de Cervantes"},
  {"pergunta": "Qual é o maior mamífero do mundo?", "resposta": "Baleia Azul"},
  {"pergunta": "Quantos anos tem um século?", "resposta": "Cem"},
  {"pergunta": "Quem pintou a Mona Lisa?", "resposta": "Leonardo da Vinci"},
  {"pergunta": "Qual é o rio mais longo do mundo?", "resposta": "Rio Amazonas"},
  {"pergunta": "Quantos lados tem um triângulo?", "resposta": "Três"},
  {"pergunta": "Qual é o maior oceano do mundo?", "resposta": "Oceano Pacífico"},
  {"pergunta": "Quem foi o primeiro presidente dos Estados Unidos?", "resposta": "George Washington"},
  {"pergunta": "Quantos continentes existem?", "resposta": "Sete"},
  {"pergunta": "Quem escreveu 'Romeu e Julieta'?", "resposta": "William Shakespeare"},
  {"pergunta": "Qual é a capital da França?", "resposta": "Paris"},
  {"pergunta": "Quantos dentes adultos uma pessoa normal tem?", "resposta": "32"},
  {"pergunta": "Quem foi o primeiro homem a pisar na lua?", "resposta": "Neil Armstrong"},
  {"pergunta": "Qual é o símbolo químico do ouro?", "resposta": "Au"},
  {"pergunta": "Quem foi o fundador da Microsoft?", "resposta": "Bill Gates"},
  {"pergunta": "Quantas patas tem um inseto?", "resposta": "Seis"},
  {"pergunta": "Qual é o maior deserto do mundo?", "resposta": "Deserto da Antártida"},
  {"pergunta": "Quem pintou 'A Noite Estrelada'?", "resposta": "Vincent van Gogh"},
  {"pergunta": "Quantos países existem na União Europeia?", "resposta": "27"},
  {"pergunta": "Quem foi o autor de 'O Pequeno Príncipe'?", "resposta": "Antoine de Saint-Exupéry"},
  {"pergunta": "Qual é a capital da Austrália?", "resposta": "Camberra"},
  {"pergunta": "Quantas câmaras tem o coração humano?", "resposta": "Quatro"},
  {"pergunta": "Quem foi o cientista que formulou a teoria da relatividade?", "resposta": "Albert Einstein"},
  {"pergunta": "Qual é o maior lago do mundo?", "resposta": "Lago Baikal"},
  {"pergunta": "Quem foi a primeira mulher a ganhar dois prêmios Nobel?", "resposta": "Marie Curie"},
  {"pergunta": "Qual é o planeta conhecido como 'Planeta Vermelho'?", "resposta": "Marte"},
  {"pergunta": "Quem foi o líder da Revolução Cubana?", "resposta": "Fidel Castro"},
  {"pergunta": "Qual é a maior cordilheira do mundo?", "resposta": "Cordilheira dos Andes"},
  {"pergunta": "Quem foi o primeiro imperador do Brasil?", "resposta": "Dom Pedro I"},
  {"pergunta": "Qual é a moeda oficial do Japão?", "resposta": "Iene"},
  {"pergunta": "Quantos ossos tem o corpo humano?", "resposta": "Cerca de 206"},
  {"pergunta": "Quem foi o pintor do quadro 'Guernica'?", "resposta": "Pablo Picasso"},
  {"pergunta": "Qual é o maior animal terrestre?", "resposta": "Elefante Africano"},
  {"pergunta": "Quem escreveu 'A Odisséia'?", "resposta": "Homero"},
  {"pergunta": "Qual é o menor país do mundo?", "resposta": "Vaticano"},
  {"pergunta": "Quem foi o criador do Facebook?", "resposta": "Mark Zuckerberg"},
  {"pergunta": "Quantos dentes de leite uma criança tem?", "resposta": "20"},
  {"pergunta": "Quem foi o autor da teoria da evolução das espécies?", "resposta": "Charles Darwin"},
  {"pergunta": "Qual é o segundo planeta do sistema solar?", "resposta": "Vênus"},
  {"pergunta": "Quem foi o primeiro presidente do Brasil eleito pelo voto direto?", "resposta": "Fernando Collor de Mello"},
  {"pergunta": "Qual é o maior órgão do corpo humano?", "resposta": "Pele"},
  {"pergunta": "Quem foi o líder da Revolução Russa?", "resposta": "Vladimir Lenin"},
  {"pergunta": "Qual é o maior estado brasileiro em área territorial?", "resposta": "Amazonas"},
  {"pergunta": "Quem escreveu 'Os Lusíadas'?", "resposta": "Luís de Camões"},
  {"pergunta": "Qual é o animal símbolo da Austrália?", "resposta": "Canguru"},
  {"pergunta": "Quem foi o inventor da lâmpada elétrica?", "resposta": "Thomas Edison"},
  {"pergunta": "Qual é o maior produtor de petróleo do mundo?", "resposta": "Arábia Saudita"},
  {"pergunta": "Quem foi o fundador da Apple?", "resposta": "Steve Jobs"},
  {"pergunta": "Qual é a maior ilha do mundo?", "resposta": "Groenlândia"},
  {"pergunta": "Quem foi o líder do movimento pelos direitos civis nos Estados Unidos?", "resposta": "Martin Luther King Jr."},
  {"pergunta": "Qual é o ponto mais alto da Terra?", "resposta": "Monte Everest"},
  {"pergunta": "Quem foi o autor de 'Crime e Castigo'?", "resposta": "Fiódor Dostoiévski"},
  {"pergunta": "Qual é o animal mais venenoso do mundo?", "resposta": "Água-viva Caixa-de-Fogo"},
  {"pergunta": "Quem foi o primeiro presidente negro da África do Sul?", "resposta": "Nelson Mandela"},
  {"pergunta": "Qual é o maior país da América do Sul?", "resposta": "Brasil"},
  {"pergunta": "Quem foi o primeiro homem a fazer uma viagem espacial?", "resposta": "Yuri Gagarin"},
  {"pergunta": "Qual é o segundo metal mais abundante na crosta terrestre?", "resposta": "Alumínio"},
  {"pergunta": "Quem foi o líder da Revolução Industrial na Inglaterra?", "resposta": "James Watt"},
  {"pergunta": "Qual é o maior deserto quente do mundo?", "resposta": "Deserto do Saara"},
  {"pergunta": "Quem foi o criador da teoria do Big Bang?", "resposta": "Georges Lemaître"},
  {"pergunta": "Qual é o maior rio da Europa?", "resposta": "Rio Volga"},
  {"pergunta": "Quem foi o fundador da Microsoft?", "resposta": "Bill Gates"},
  {"pergunta": "Qual é o maior animal marinho?", "resposta": "Baleia Azul"},
  {"pergunta": "Quem foi o primeiro homem a pisar na lua?", "resposta": "Neil Armstrong"},
  {"pergunta": "Qual é o país mais populoso do mundo?", "resposta": "China"},
  {"pergunta": "Quem foi o inventor do telefone?", "resposta": "Alexander Graham Bell"},
  {"pergunta": "Qual é o maior lago da África?", "resposta": "Lago Vitória"},
  {"pergunta": "Quem foi o autor de 'Cem Anos de Solidão'?", "resposta": "Gabriel García Márquez"},
  {"pergunta": "Qual é o país mais extenso do mundo?", "resposta": "Rússia"},
  {"pergunta": "Quem foi o primeiro presidente do Brasil?", "resposta": "Marechal Deodoro da Fonseca"},
  {"pergunta": "Qual é o animal mais rápido do planeta?", "resposta": "Falcão-peregrino"},
  {"pergunta": "Quem foi o autor de 'O Senhor dos Anéis'?", "resposta": "J.R.R. Tolkien"},
  {"pergunta": "Qual é o maior produtor de café do mundo?", "resposta": "Brasil"},
  {"pergunta": "Quem foi o primeiro imperador romano?", "resposta": "César Augusto"},
  {"pergunta": "Qual é o país mais populoso da América do Sul?", "resposta": "Brasil"},
  {"pergunta": "Quem foi o primeiro homem a completar uma volta ao mundo?", "resposta": "Ferdinand Magalhães"},
  {"pergunta": "Qual é o menor osso do corpo humano?", "resposta": "Estribo"},
  {"pergunta": "Quem foi o autor de 'O Príncipe'?", "resposta": "Maquiavel"},
  {"pergunta": "Qual é o maior produtor de vinho do mundo?", "resposta": "Itália"},
  {"pergunta": "Quem foi o primeiro homem a chegar ao Polo Sul?", "resposta": "Roald Amundsen"},
  {"pergunta": "Qual é o país mais rico do mundo?", "resposta": "Luxemburgo"},
  {"pergunta": "Quem foi o pintor do quadro 'A Última Ceia'?", "resposta": "Leonardo da Vinci"},
  {"pergunta": "Qual é o maior produtor de cerveja do mundo?", "resposta": "China"},
  {"pergunta": "Quem foi o autor de 'Ulisses'?", "resposta": "James Joyce"},
  {"pergunta": "Qual é o maior produtor de petróleo da África?", "resposta": "Nigéria"},
  {"pergunta": "Quem foi o primeiro homem a alcançar o cume do Monte Everest?", "resposta": "Sir Edmund Hillary"},
  {"pergunta": "Qual é o país mais populoso da Europa?", "resposta": "Alemanha"},
  {"pergunta": "Quem foi o líder da Revolução Cubana?", "resposta": "Fidel Castro"},
  {"pergunta": "Qual é o animal mais venenoso do planeta?", "resposta": "Água-viva Caixa-de-Fogo"},
  {"pergunta": "Quem foi o primeiro presidente dos Estados Unidos?", "resposta": "George Washington"},
  {"pergunta": "Qual é o maior rio do mundo em volume de água?", "resposta": "Rio Amazonas"},
  {"pergunta": "Quem foi o autor de 'Os Miseráveis'?", "resposta": "Victor Hugo"},
  {"pergunta": "Qual é o maior oceano do mundo?", "resposta": "Oceano Pacífico"},
  {"pergunta": "Quem foi o primeiro homem a orbitar a Terra?", "resposta": "Iuri Gagarin"},
  {"pergunta": "Qual é o maior deserto do mundo em área?", "resposta": "Deserto da Antártida"},
  {"pergunta": "Quem foi o autor de 'O Retrato de Dorian Gray'?", "resposta": "Oscar Wilde"},
  {"pergunta": "Qual é o menor país da América do Sul?", "resposta": "Suriname"},
  {"pergunta": "Quem foi o líder da Revolução Industrial na Inglaterra?", "resposta": "James Watt"},
  {"pergunta": "Qual é o maior lago do mundo em volume de água?", "resposta": "Lago Baikal"},
  {"pergunta": "Quem foi o primeiro homem a fazer uma viagem espacial?", "resposta": "Yuri Gagarin"},
  {"pergunta": "Qual é o símbolo químico do ouro?", "resposta": "Au"},
  {"pergunta": "Quem foi o líder da Revolução Russa?", "resposta": "Vladimir Lenin"},
  {"pergunta": "Qual é o maior rio do Brasil?", "resposta": "Rio Amazonas"},
  {"pergunta": "Quem foi o autor de 'O Primo Basílio'?", "resposta": "José Maria de Eça de Queirós"},
  {"pergunta": "Qual é o país mais populoso do mundo?", "resposta": "China"},
  {"pergunta": "Quem foi o primeiro homem a pisar na Lua?", "resposta": "Neil Armstrong"},
  {"pergunta": "Qual é o animal símbolo da Austrália?", "resposta": "Canguru"}
];